export enum GrayscaleLight {
    BACKGROUND_LAYER_1 = '#F5F5F5',
    BACKGROUND_LAYER_1_HIGHLIGHT = '#E1E1E1',
    BACKGROUND_LAYER_2 = '#EBEBEB',
    BACKGROUND_LAYER_FOCUS = '#E0E0E0',
    LAYER_BORDER = '#CCCCCC',
    FOREGROUND = '#141414',
    PRIMARY_CONTRAST = '#F5F5F5',
}
