name: Publish Released

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install 
        run: npm install

      - name: Publish to Marketplace
        run: npm run vsce-publish -- -p $VSCE_AZURE_PAT
        env:
          VSCE_AZURE_PAT: ${{ secrets.VSCE_AZURE_PAT }}