name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install
        run: npm install

      - name: Package Extension
        run: npm run package
      
      - name: Semantic Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Marketplace
        run: npm run vsce-publish -- -p $VSCE_AZURE_PAT
        env:
          VSCE_AZURE_PAT: ${{ secrets.VSCE_AZURE_PAT }}

